### ISSUE TITLE
Unable To Move Through Faction Territory

### ISSUE THREAD

**Issue by GalacticCraft** [eirikh1996/Movecraft-Factions#1]
**Describe the bug**
Ships are unable to pass through owned or friendly faction territory.

**To Reproduce**
1. Pilot the ship.
2. Attempt to move it through your own faction territory or another.
3. The error will make itself appear.

**Expected behavior**
Ships should be able to pass through friendly territory, such as your own territory and allied territories.

**Additional context**
If there's an option being planned to disable or enable passthrough for certain factions only, that'd be nice. Like, all factions will HAVE to let ships through by default, and only the server owner can edit the config for specific factions to allow or disallow passthrough. I'd also maybe like an option for factions to enable or disable passthrough by themselves, like a faction flag. There should also be an option to make the flag editable or not.

**Comment by eirikh1996** [comment]
Fixed in commit 59713a5d20649abe7342f638ac7c63661717c0d5
