### ISSUE TITLE
Navigation Sign

### ISSUE THREAD

**Issue by GalacticCraft** [eirikh1996/Movecraft-Factions#2]
**Describe the feature you'd like**
A Navigation sign that displays the current coordinates of the sign itself. It'd probably be laggy to do, especially if the sign has to change coordinates every block. the basic idea is that it would be a display sign to give you the current coordinates of your ship. The sign would be created by putting "Navigation:" on the top line, and it would automatically activate.

**Additional context**
The sign would look like this:
(Example)
Navigation:
X: 903
Y: 140
Z: 919

**Comment by eirikh1996** [comment]
That would have to be made as a separate plugin and not as part of Movecraft-Factions

**Comment by GalacticCraft** [comment]
I'll move that to the official Movecraft page then.
