### ISSUE TITLE
Radio Sign

### ISSUE THREAD

**Issue by GalacticCraft** [eirikh1996/Movecraft-Factions#3]
**Describe the feature you'd like**
A sign that allows communications between ships that are or are not being piloted. The sign would have the option of switching between 999 different channels. The user would right click the sign to change the number, and shift right click the sign to choose which number to change. They would also be able to set the channel with a command, such as "/radio 983" which would set their channel to 983. Anyone within 30 blocks of the radio sign would be able to hear it if the radio itself is set to a channel that has another radio sign communicating in from, opposed to having to currently be piloting a craft. It wouldn't rely on multiple users all having to have radios set to the same frequency. It relies on two radios, each having the same frequency, with any number of users communicating from both sides.

**Additional context**
The sign would look like this:
(Example)
Radio:
9-8-3
^----
(The arrow would be the number currently being changed if right clicked. Shift right clicking will change which number you want to set.)
Radio:
9-8-3
--^--

**Comment by eirikh1996** [comment]
That will be made as a separate Movecraft extension, not as part of Movecraft-Factions

**Comment by GalacticCraft** [comment]
I'll move that to the official Movecraft page then.
